### PR TITLE
Some updates and fixes

### PR DESCRIPTION
**Pull request by ATFmxyl**
Added missing simplified Chinese

### CODE REVIEW

**Comment by SayantanRC** [comment]
:+1:

**Comment by ATFmxyl** [comment]
> 👍
The current version is not the latest (・∀・(・∀・(・∀・*)

**Comment by SayantanRC** [comment]
:( Yeah. I will post the strings for version 5. Skipping version 4 altogether. Version 5 still requires some work.

**Comment by ATFmxyl** [comment]
> :( Yeah. I will post the strings for version 5. Skipping version 4 altogether. Version 5 still requires some work.

Everyone has been busy lately 😭

**Comment by SayantanRC** [comment]
Here in India we are more concerned with staying alive in the first place 😂

**Pull request merged**
