### PR TITLE
Traducciones

### PR DESCRIPTION
**Pull request by peter9811**

### CODE REVIEW

**Comment by SayantanRC** [comment]
Whoa! You translated Power menu controls too! This is really nice. Thank you.

**Comment by peter9811** [comment]
Thank you, for your hard work

So fast to copy 115 apps on Android 11

**Comment by SayantanRC** [comment]
Hi. Sorry to bother. It was thinking if you had the time, could you please translate the new strings_4.xml file for Power Menu Controls? 
Its fine if you can't. But I thought it would be okay to ask.
Thank you.

**Comment by peter9811** [comment]
Thanks for thinking of me. I have no problem, get on it right now

Thanks to you, for excellent app

**Comment by peter9811** [comment]
And, if you want, try upload the translations to Crowdin, it's so good place to stay organized, see my personal project to migrate: https://crowdin.com/project/traducciones-mas/es-ES#

**Comment by SayantanRC** [comment]
Yeah crowdin would have been great, but isnt it paid? You are a paid user?

**Comment by peter9811** [comment]
It's free. I have a lot of projects
If you don't need "premium" features, you can use it without problems

**Comment by SayantanRC** [comment]
Cool. I will check it.

**Comment by peter9811** [comment]
Thanks for taking my idea.
Hope you like Crowdin

And if you want, I can become the "reviewer" of Spanish and also help to translate completely into Spanish

**Comment by SayantanRC** [comment]
Here is the project: https://crowdin.com/project/power-menu-controls

**Comment by peter9811** [comment]
Yes, I checked it out already, but you didn't add spanish ): 

I'm going to continue translating on my project. When I finished with it I'm going to add to pull request

**Pull request merged**
