### PR TITLE
Update id&ru translations

### PR DESCRIPTION
**Pull request by rzlamrr**
I also update readme:) Just my opnion

### CODE REVIEW

**Comment by SayantanRC** [comment]
nice suggestion in README

**Comment by SayantanRC** [comment]
Changing language to Indonesian in the settings is not being reflected with locale `id`.
But working with locale `in`. Please check :)

**Comment by rzlamrr** [comment]
Ah i see, sometime i confused between `id` and `in`. I think `in` is for India

**Comment by SayantanRC** [comment]
I think it's safer to keep both files. strings-id.xml and strings-in.xml

**Comment by SayantanRC** [comment]
Hello.
It would be great if you could provide translation for the strings in migrate helper.
Thanks. :)

**Pull request merged**
