### PR TITLE
Update strings-tr_20.xml

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by SayantanRC — CHANGES_REQUESTED** [review]
You could update the filename to strings-tr_20.xml

**Comment by SayantanRC** [comment]
You just changed the title. 😂

**Comment by SayantanRC** [comment]
Lovely. Merging.

**Comment by ghost** [comment]
> You just changed the title.
Sorry :)

**Comment by SayantanRC** [comment]
No problem :+1:

**Pull request merged**
